import type { ServiceDefinition } from "@/lib/providers/provider";

export const serviceCatalog: ServiceDefinition[] = [
  { id: "openai", name: "OpenAI", category: "ai", enabled: true },
  { id: "azure-ai", name: "Azure AI", category: "ai", enabled: true },
  { id: "hugging-face-spaces", name: "Hugging Face Spaces", category: "ai", enabled: true },
  { id: "zen-arena", name: "ZEN Arena", category: "custom", enabled: true },
  { id: "anthropic", name: "Anthropic", category: "ai", enabled: false },
  { id: "cohere", name: "Cohere", category: "ai", enabled: false },
  { id: "supabase", name: "Supabase", category: "database", enabled: true },
  { id: "postgres-primary", name: "Postgres Primary", category: "database", enabled: true },
  { id: "redis-cache", name: "Redis Cache", category: "database", enabled: true },
  { id: "vercel", name: "Vercel", category: "infra", enabled: true },
  { id: "github", name: "GitHub", category: "source-control", enabled: true },
  { id: "github-actions", name: "GitHub Actions", category: "source-control", enabled: true },
  { id: "stripe", name: "Stripe", category: "billing", enabled: true },
  { id: "notion", name: "Notion", category: "knowledge", enabled: true },
  { id: "wix", name: "Wix", category: "custom", enabled: true },
  { id: "discord", name: "Discord", category: "messaging", enabled: true },
  { id: "google-cloud", name: "Google Cloud", category: "infra", enabled: true },
  { id: "gcp-monitoring", name: "GCP Monitoring", category: "infra", enabled: true },
  { id: "cloud-run", name: "Cloud Run", category: "infra", enabled: true },
  { id: "cloud-sql", name: "Cloud SQL", category: "database", enabled: true },
  { id: "bigquery", name: "BigQuery", category: "analytics", enabled: true },
  { id: "datadog", name: "Datadog", category: "analytics", enabled: true },
  { id: "sentry", name: "Sentry", category: "analytics", enabled: true },
  { id: "grafana", name: "Grafana", category: "analytics", enabled: true },
  { id: "prometheus", name: "Prometheus", category: "analytics", enabled: true },
  { id: "segment", name: "Segment", category: "analytics", enabled: true },
  { id: "mixpanel", name: "Mixpanel", category: "analytics", enabled: true },
  { id: "plausible", name: "Plausible", category: "analytics", enabled: true },
  { id: "google-analytics", name: "Google Analytics", category: "analytics", enabled: true },
  { id: "cloudflare", name: "Cloudflare", category: "infra", enabled: true },
  { id: "aws-s3", name: "AWS S3", category: "infra", enabled: false },
  { id: "aws-lambda", name: "AWS Lambda", category: "infra", enabled: false },
  { id: "helm", name: "Helm", category: "infra", enabled: true },
  { id: "kubernetes", name: "Kubernetes", category: "infra", enabled: true },
  { id: "docker-registry", name: "Docker Registry", category: "infra", enabled: true },
  { id: "rabbitmq", name: "RabbitMQ", category: "infra", enabled: true },
  { id: "kafka", name: "Kafka", category: "infra", enabled: true },
  { id: "nats", name: "NATS", category: "infra", enabled: true },
  { id: "twilio", name: "Twilio", category: "messaging", enabled: false },
  { id: "slack", name: "Slack", category: "messaging", enabled: false },
  { id: "telegram", name: "Telegram", category: "messaging", enabled: false },
  { id: "mailgun", name: "Mailgun", category: "messaging", enabled: true },
  { id: "sendgrid", name: "SendGrid", category: "messaging", enabled: true },
  { id: "alchemy", name: "Alchemy", category: "blockchain", enabled: true },
  { id: "quicknode", name: "QuickNode", category: "blockchain", enabled: true },
  { id: "polygon-ledger", name: "Polygon Credential Ledger", category: "blockchain", enabled: true },
  { id: "ethereum-ledger", name: "Ethereum Credential Ledger", category: "blockchain", enabled: true },
  { id: "snowflake", name: "Snowflake", category: "analytics", enabled: false },
  { id: "airbyte", name: "Airbyte", category: "analytics", enabled: true },
  { id: "dbt-cloud", name: "dbt Cloud", category: "analytics", enabled: true },
  { id: "retool", name: "Retool", category: "custom", enabled: false },
  { id: "crowdsec", name: "CrowdSec", category: "infra", enabled: true },
  { id: "vault", name: "HashiCorp Vault", category: "infra", enabled: true },
  { id: "fastly", name: "Fastly", category: "infra", enabled: false },
  { id: "pinecone", name: "Pinecone", category: "database", enabled: true }
];
